include ../tools/Makefile.base
# Customization hooks for xsltproc options
HTML_XSLTPROC_OPTS = --stringparam l10n.gentext.language de
FO_XSLTPROC_OPTS = --param fop1.extensions 1 --param fop.extensions 0 --stringparam paper.type A4 --stringparam l10n.gentext.language de
