export FOP_CFG=-c fop.xconf
include ../tools/Makefile.base
HTML_XSLTPROC_OPTS = --stringparam l10n.gentext.language zh_cn
FO_XSLTPROC_OPTS = --param fop1.extensions 1 --stringparam l10n.gentext.language zh_cn
L10N_REVISION = r
